CC = c++
CFLAGS = -Wall -Wextra -Werror -std=c++98 -g -fsanitize=address -Wshadow
RM = rm -rf
NAME = main

FILES = main.cpp Brain.cpp\
	$(addprefix ./previous/, AAnimal.cpp Cat.cpp Dog.cpp)

all: $(NAME)

$(NAME):
	$(CC) $(CFLAGS) -o $(NAME) $(FILES)

run:
	./$(NAME)

valgrind:
	valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --verbose ./$(NAME)

clean:
	$(RM) $(NAME)

re: clean all